appVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }} 
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec: 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: ASP_CORE_ENVIRONMENT
              value: {{ .Values.config.ASP_CORE_ENVIRONMENT }}
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: ConnectionStrings__DefaultConnection
            - name: Redis__Configuration
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: Redis__Configuration
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 -}}